version: '2'
services:
    testapplication-app:
        image: testapplication
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://testapplication-postgresql:5432/testApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testapplication-postgresql:
        extends:
            file: postgresql.yml
            service: testapplication-postgresql
